# Plane Wave Operators

# 1D

In [26]:
import numpy as np
k_min = -16
k_max = 15
k_point_grid = np.arange(k_min, k_max+1)
k_dim = len(k_point_grid)



In [27]:
from grid1q.operators.plane_wave import kenetic, elec_nuc_potential, plane_wave_hamiltonian
print("k_point_grid", k_point_grid)
k_point_grid_array = [np.array([k]) for k in k_point_grid]

kenetic(k_point_grid_array)

k_point_grid [-16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1
   2   3   4   5   6   7   8   9  10  11  12  13  14  15]


array([[32768. ,     0. ,     0. , ...,     0. ,     0. ,     0. ],
       [    0. , 25312.5,     0. , ...,     0. ,     0. ,     0. ],
       [    0. ,     0. , 19208. , ...,     0. ,     0. ,     0. ],
       ...,
       [    0. ,     0. ,     0. , ..., 14280.5,     0. ,     0. ],
       [    0. ,     0. ,     0. , ...,     0. , 19208. ,     0. ],
       [    0. ,     0. ,     0. , ...,     0. ,     0. , 25312.5]])

In [28]:
cell_area = 1.0
r_pos = [np.array([0.5])]

elec_nuc_potential(k_point_grid_array, cell_area, r_pos)

array([[ 0.00000000e+00+0.00000000e+00j,  1.10280277e+01+6.02463900e+00j,
         1.69740975e+00+2.64355906e+00j, ...,
        -5.30334111e-03+1.39693671e-02j, -1.06072443e-02+9.07973112e-03j,
        -1.27945982e-02+2.69984068e-03j],
       [ 1.10280277e+01-6.02463900e+00j,  0.00000000e+00+0.00000000e+00j,
         1.10280277e+01+6.02463900e+00j, ...,
         2.19169714e-03+1.58779836e-02j, -5.30334111e-03+1.39693671e-02j,
        -1.06072443e-02+9.07973112e-03j],
       [ 1.69740975e+00-2.64355906e+00j,  1.10280277e+01-6.02463900e+00j,
         0.00000000e+00+0.00000000e+00j, ...,
         1.02551352e-02+1.38554911e-02j,  2.19169714e-03+1.58779836e-02j,
        -5.30334111e-03+1.39693671e-02j],
       ...,
       [-5.30334111e-03-1.39693671e-02j,  2.19169714e-03-1.58779836e-02j,
         1.02551352e-02-1.38554911e-02j, ...,
         0.00000000e+00+0.00000000e+00j,  1.10280277e+01+6.02463900e+00j,
         1.69740975e+00+2.64355906e+00j],
       [-1.06072443e-02-9.07973112e-03j, -5.

In [29]:
H = plane_wave_hamiltonian(k_point_grid_array, cell_area, r_pos)

In [30]:
from numpy.linalg import eig
eig(H)

EigResult(eigenvalues=array([ 3.27680221e+04+1.23821474e-19j,  2.53124988e+04+2.32376520e-13j,
        2.53125339e+04+3.01229805e-13j,  1.92079911e+04+2.55008295e-12j,
        1.92080233e+04+2.44252438e-12j,  1.42805278e+04-1.16809356e-13j,
        1.42804904e+04-8.20903748e-14j,  1.03680344e+04-8.66673123e-13j,
        1.03679905e+04-7.63644863e-13j,  7.32054378e+03+3.76395777e-13j,
        7.32049147e+03+3.73675432e-13j,  5.00005758e+03+3.86967443e-13j,
        4.99999407e+03+3.72729374e-13j,  3.28057887e+03-5.63579746e-14j,
        3.28050002e+03-2.32831416e-14j,  2.04811378e+03-8.18966836e-13j,
        2.04801297e+03-6.41683492e-13j,  1.20067577e+03-1.64604146e-13j,
        1.20054155e+03-1.76918298e-13j,  6.48298251e+02-1.13196318e-13j,
        6.48108058e+02-8.14439229e-14j,  3.13080431e+02-3.52855583e-13j,
        3.12778337e+02-9.41276609e-14j,  1.29420828e+02+6.04343696e-15j,
        1.28784694e+02+2.09377945e-13j,  4.63442489e+01-6.29517230e-14j,
        4.29600370e+01+4.2606

# 2D

In [31]:
import itertools
import numpy as np
k_min = -16
k_max = 15
ks = np.arange(k_min, k_max+1)
k_dim = len(ks)
k_point_grid = list(itertools.product(ks, ks))
print(k_point_grid)
k_point_grid_array = [np.array(k) for k in k_point_grid]

[(-16, -16), (-16, -15), (-16, -14), (-16, -13), (-16, -12), (-16, -11), (-16, -10), (-16, -9), (-16, -8), (-16, -7), (-16, -6), (-16, -5), (-16, -4), (-16, -3), (-16, -2), (-16, -1), (-16, 0), (-16, 1), (-16, 2), (-16, 3), (-16, 4), (-16, 5), (-16, 6), (-16, 7), (-16, 8), (-16, 9), (-16, 10), (-16, 11), (-16, 12), (-16, 13), (-16, 14), (-16, 15), (-15, -16), (-15, -15), (-15, -14), (-15, -13), (-15, -12), (-15, -11), (-15, -10), (-15, -9), (-15, -8), (-15, -7), (-15, -6), (-15, -5), (-15, -4), (-15, -3), (-15, -2), (-15, -1), (-15, 0), (-15, 1), (-15, 2), (-15, 3), (-15, 4), (-15, 5), (-15, 6), (-15, 7), (-15, 8), (-15, 9), (-15, 10), (-15, 11), (-15, 12), (-15, 13), (-15, 14), (-15, 15), (-14, -16), (-14, -15), (-14, -14), (-14, -13), (-14, -12), (-14, -11), (-14, -10), (-14, -9), (-14, -8), (-14, -7), (-14, -6), (-14, -5), (-14, -4), (-14, -3), (-14, -2), (-14, -1), (-14, 0), (-14, 1), (-14, 2), (-14, 3), (-14, 4), (-14, 5), (-14, 6), (-14, 7), (-14, 8), (-14, 9), (-14, 10), (-14, 1

In [34]:
kenetic(k_point_grid_array)

array([[131072. ,      0. ,      0. , ...,      0. ,      0. ,      0. ],
       [     0. , 115680.5,      0. , ...,      0. ,      0. ,      0. ],
       [     0. ,      0. , 102152. , ...,      0. ,      0. ,      0. ],
       ...,
       [     0. ,      0. ,      0. , ...,  77618. ,      0. ,      0. ],
       [     0. ,      0. ,      0. , ...,      0. ,  88620.5,      0. ],
       [     0. ,      0. ,      0. , ...,      0. ,      0. , 101250. ]])

In [35]:
cell_area = 1.0
r_pos = [np.array([0.5, 0.5])]

elec_nuc_potential(k_point_grid_array, cell_area, r_pos)

array([[ 0.00000000e+00+0.00000000e+00j,  1.10280277e+01+6.02463900e+00j,
         1.69740975e+00+2.64355906e+00j, ...,
         1.07568307e-03-6.89010631e-03j,  4.11264004e-03-5.35557810e-03j,
         5.98074479e-03-2.64166847e-03j],
       [ 1.10280277e+01-6.02463900e+00j,  0.00000000e+00+0.00000000e+00j,
         1.10280277e+01+6.02463900e+00j, ...,
        -2.43635793e-03-6.77670455e-03j,  1.07568307e-03-6.89010631e-03j,
         4.11264004e-03-5.35557810e-03j],
       [ 1.69740975e+00-2.64355906e+00j,  1.10280277e+01-6.02463900e+00j,
         0.00000000e+00+0.00000000e+00j, ...,
        -5.56234802e-03-4.93459724e-03j, -2.43635793e-03-6.77670455e-03j,
         1.07568307e-03-6.89010631e-03j],
       ...,
       [ 1.07568307e-03+6.89010631e-03j, -2.43635793e-03+6.77670455e-03j,
        -5.56234802e-03+4.93459724e-03j, ...,
         0.00000000e+00+0.00000000e+00j,  1.10280277e+01+6.02463900e+00j,
         1.69740975e+00+2.64355906e+00j],
       [ 4.11264004e-03+5.35557810e-03j,  1.

In [36]:
H = plane_wave_hamiltonian(k_point_grid_array, cell_area, r_pos)

In [37]:
eig(H)

EigResult(eigenvalues=array([131072.02321078+5.23959887e-17j, 115686.80698418+3.85737021e-11j,
       115680.5320558 +3.74401013e-11j, ...,
          304.10228353-4.18538792e-13j,    306.55513357+3.13999998e-12j,
          306.475703  -1.00847071e-13j]), eigenvectors=array([[ 9.99999291e-01+0.00000000e+00j, -1.01454921e-03-5.54250758e-04j,
        -3.71840713e-06+7.84636353e-07j, ...,
         2.69933325e-19-1.24851429e-18j, -7.01669247e-19-5.99387348e-19j,
        -5.79863769e-19+2.68965991e-19j],
       [ 7.17099723e-04-3.91753364e-04j,  7.07098625e-01+0.00000000e+00j,
         2.32815378e-03-1.99288427e-03j, ...,
         8.37587180e-10+3.87820549e-10j,  9.77154536e-10+1.48126332e-10j,
        -1.96682682e-10-2.98150158e-11j],
       [ 5.89874892e-05-9.18675713e-05j,  6.92168559e-04-3.78133407e-04j,
         6.91787283e-07-1.82221553e-06j, ...,
         2.43474171e-09-1.61833009e-10j,  2.46554908e-09-8.98755077e-10j,
        -5.23800804e-10+1.90938670e-10j],
       ...,
       [ 2.0

# 3D

In [38]:
import itertools
import numpy as np
k_min = -8
k_max = 7
ks = np.arange(k_min, k_max+1)
k_dim = len(ks)
print(k_dim, ks)
k_point_grid = list(itertools.product(ks, ks, ks))
print(len(k_point_grid))

16 [-8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7]
4096


In [39]:
print("k_point_grid", k_point_grid)
k_point_grid_array = [np.array(k) for k in k_point_grid]

kenetic(k_point_grid_array)

k_point_grid [(-8, -8, -8), (-8, -8, -7), (-8, -8, -6), (-8, -8, -5), (-8, -8, -4), (-8, -8, -3), (-8, -8, -2), (-8, -8, -1), (-8, -8, 0), (-8, -8, 1), (-8, -8, 2), (-8, -8, 3), (-8, -8, 4), (-8, -8, 5), (-8, -8, 6), (-8, -8, 7), (-8, -7, -8), (-8, -7, -7), (-8, -7, -6), (-8, -7, -5), (-8, -7, -4), (-8, -7, -3), (-8, -7, -2), (-8, -7, -1), (-8, -7, 0), (-8, -7, 1), (-8, -7, 2), (-8, -7, 3), (-8, -7, 4), (-8, -7, 5), (-8, -7, 6), (-8, -7, 7), (-8, -6, -8), (-8, -6, -7), (-8, -6, -6), (-8, -6, -5), (-8, -6, -4), (-8, -6, -3), (-8, -6, -2), (-8, -6, -1), (-8, -6, 0), (-8, -6, 1), (-8, -6, 2), (-8, -6, 3), (-8, -6, 4), (-8, -6, 5), (-8, -6, 6), (-8, -6, 7), (-8, -5, -8), (-8, -5, -7), (-8, -5, -6), (-8, -5, -5), (-8, -5, -4), (-8, -5, -3), (-8, -5, -2), (-8, -5, -1), (-8, -5, 0), (-8, -5, 1), (-8, -5, 2), (-8, -5, 3), (-8, -5, 4), (-8, -5, 5), (-8, -5, 6), (-8, -5, 7), (-8, -4, -8), (-8, -4, -7), (-8, -4, -6), (-8, -4, -5), (-8, -4, -4), (-8, -4, -3), (-8, -4, -2), (-8, -4, -1), (-8, -4, 0

array([[18432. ,     0. ,     0. , ...,     0. ,     0. ,     0. ],
       [    0. , 15664.5,     0. , ...,     0. ,     0. ,     0. ],
       [    0. ,     0. , 13448. , ...,     0. ,     0. ,     0. ],
       ...,
       [    0. ,     0. ,     0. , ...,  7564.5,     0. ,     0. ],
       [    0. ,     0. ,     0. , ...,     0. ,  8978. ,     0. ],
       [    0. ,     0. ,     0. , ...,     0. ,     0. , 10804.5]])

In [40]:
cell_area = 1.0
r_pos = [np.array([0.5, 0.5, 0.5])]
elec_nuc_potential(k_point_grid_array, cell_area, r_pos)

array([[ 0.00000000e+00+0.00000000e+00j,  1.10280277e+01+6.02463900e+00j,
         1.69740975e+00+2.64355906e+00j, ...,
        -1.79013274e-02+9.57478273e-03j, -1.94518241e-02-1.72180856e-04j,
        -1.62581774e-02-9.06965256e-03j],
       [ 1.10280277e+01-6.02463900e+00j,  0.00000000e+00+0.00000000e+00j,
         1.10280277e+01+6.02463900e+00j, ...,
        -1.15874897e-02+1.76998735e-02j, -1.79013274e-02+9.57478273e-03j,
        -1.94518241e-02-1.72180856e-04j],
       [ 1.69740975e+00-2.64355906e+00j,  1.10280277e+01-6.02463900e+00j,
         0.00000000e+00+0.00000000e+00j, ...,
        -1.75100748e-03+2.19378855e-02j, -1.15874897e-02+1.76998735e-02j,
        -1.79013274e-02+9.57478273e-03j],
       ...,
       [-1.79013274e-02-9.57478273e-03j, -1.15874897e-02-1.76998735e-02j,
        -1.75100748e-03-2.19378855e-02j, ...,
         0.00000000e+00+0.00000000e+00j,  1.10280277e+01+6.02463900e+00j,
         1.69740975e+00+2.64355906e+00j],
       [-1.94518241e-02+1.72180856e-04j, -1.

In [41]:
H = plane_wave_hamiltonian(k_point_grid_array, cell_area, r_pos)

In [42]:
eig(H)

EigResult(eigenvalues=array([18432.22138309+4.18385584e-15j, 15677.54328129+5.17909258e-11j,
       15664.81454373+2.69496088e-12j, ...,
        1243.40770297-2.12774243e-13j,   834.19237979-4.71956263e-13j,
        1243.43708311+4.24947778e-13j]), eigenvectors=array([[ 9.99964420e-01+0.00000000e+00j, -7.00916462e-03-3.82912408e-03j,
         2.92523721e-05+7.91573244e-05j, ...,
        -6.74179451e-19+3.10452846e-18j, -5.31928882e-19-2.05009148e-19j,
        -4.50864009e-18-9.48092593e-19j],
       [ 4.02606712e-03-2.19945049e-03j,  5.77195558e-01+0.00000000e+00j,
        -6.75036419e-03-5.88259126e-03j, ...,
         1.41684468e-08+1.91225791e-08j,  9.94196445e-08-4.49690621e-08j,
        -1.60964667e-08+1.60065446e-08j],
       [ 3.55145099e-04-5.53105720e-04j,  4.08080205e-03-2.22935232e-03j,
        -1.81512837e-05-3.99831398e-06j, ...,
         9.76982364e-09+4.51767428e-09j,  2.03353095e-07-2.69720291e-07j,
         4.05554375e-09-1.36802398e-08j],
       ...,
       [-1.8496862